name: Deploy to Cloudflare Pages

on:
  release:
    types: [published]

env:
  PROJECT_NAME: personal-website
  BUILD_DIR: dist

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: last-release-artifact
          path: ./dist

      - name: Display structure of downloaded files
        run: ls -R ./dist
      
      - name: Extract release artifact
        run: tar -xzvf ./dist/dist.tar.gz

      - name: Display structure of downloaded files
        run: ls -R ./dist
      
      # - name: Deploy
      #   uses: cloudflare/wrangler-action@v3
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #     command: pages deploy ${{ env.BUILD_DIR }} --project-name=${{ env.PROJECT_NAME }}
